[package]
name = "hex_to_rgb"
version = "0.1.0"
authors = ["Ben Santora"]
edition = "2018"
description = "A simple Rust library to convert hex color codes to RGB values."
license = "MIT"
repository = "https://github.com/bensatlantik/hex_to_rgb"

readme = "README.md"

